name = "happy-haseyeon"
compatibility_date = "2026-07-20"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "happy-haseyeon-db"
database_id = "16086623-d507-4504-b5f6-30714c37d4b3"
preview_database_id = "16086623-d507-4504-b5f6-30714c37d4b3"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "happy-haseyeon-r2"

[vars]
R2_PUBLIC_URL = "https://pub-0d79669bad084bcd94df5093066b951f.r2.dev"
